name = "Vlasiator"
uuid = "7d2ba682-ad6e-4e20-80d9-3f2d4a610bb4"
authors = ["Hongyang Zhou <hongyang.zhou@helsinki.fi>"]
version = "0.7.8"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LazyGrids = "7031d0ef-c40d-4431-b2f8-61a8d2f650db"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
FLoops = "0.1"
LaTeXStrings = "1.2"
LazyGrids = "0.2"
LightXML = "0.9"
PyPlot = "2.9"
RecipesBase = "1.1"
Requires = "1.1"
StaticArrays = "1.2"
UnPack = "1.0"
WriteVTK = "1.10"
julia = "1.6"

[extras]
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[targets]
test = ["Test", "ZipFile", "SHA"]
